# Use a imagem oficial do Python com a versão desejada
FROM python:3.9

# Instale as dependências necessárias
RUN apt-get update \
    && apt-get install -y firefox-esr \
    && rm -rf /var/lib/apt/lists/*

# Crie e configure o diretório de trabalho
WORKDIR /app

# Copie o código-fonte para o diretório de trabalho
COPY . /app

# Instale as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Comando para rodar o script de teste
CMD ["python", "./test.spec.py"]
